# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardianapp', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reported_by',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
